# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d49c071b8021b3c1fa0c803aa8d528ed9483727b836cc0230282004856dc8510e4592678acf02b0ebfe4a354dcf29b4a56a1b6ddac82c3df0729d4410a0db663

test:
  secret_key_base: 18d3be02d7ea4d5686755cfcf7e3c357e8f6af6144fba59e430308b7f33f50d0a1304c279a73b841fec6fb941ffb9ad54b47202fc7ea2387c3df7bccf037b316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
